import { Command } from "commander";
import chalk from "chalk";
import { execa } from "execa";
import { confirm, select, input, password, number } from "@inquirer/prompts";
import { writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";

const program = new Command();

program
  .name("evently")
  .description("Evently CLI - Event Management Platform")
  .version("0.1.0");

// API URL configuration
const API_URL = process.env.EVENTLY_API_URL || "http://localhost:3001";
const WEB_URL = process.env.EVENTLY_WEB_URL || "http://localhost:3000";

program
  .command("setup")
  .description("Interactive setup wizard - generates .env and starts services")
  .action(async () => {
    console.log(chalk.bold.blue("\nEvently Setup Wizard\n"));

    const rootPath = process.cwd();
    const envPath = join(rootPath, ".env");

    // Check if .env already exists
    if (existsSync(envPath)) {
      const overwrite = await confirm({
        message: ".env file already exists. Overwrite?",
        default: false,
      });
      if (!overwrite) {
        console.log(chalk.yellow("Setup cancelled."));
        return;
      }
    }

    // Ask for environment variables
    const environment = await select({
      message: "Select environment:",
      choices: [
        { value: "development", name: "development" },
        { value: "production", name: "production" },
        { value: "test", name: "test" },
      ],
      default: "development",
    });

    const apiPort = await number({
      message: "API Port:",
      default: 3001,
    });

    const dbUrl = await input({
      message: "Database URL:",
      default: "postgresql://postgres:password@localhost:5432/evently",
    });

    const webApiUrl = await input({
      message: "Web API URL:",
      default: "http://localhost:3001",
    });

    const generateSecret = await confirm({
      message: "Generate secure JWT_SECRET automatically?",
      default: true,
    });

    let jwtSecret = "";
    if (generateSecret) {
      jwtSecret = randomBytes(32).toString("hex");
      console.log(chalk.green("Generated secure JWT_SECRET"));
    } else {
      jwtSecret = await password({
        message: "Enter JWT_SECRET (min 8 characters):",
        validate: (val) =>
          val.length >= 8 || "JWT_SECRET must be at least 8 characters",
      });
    }

    // Generate .env file
    const envContent = `# Generated by Evently CLI
# Database
DATABASE_URL="${dbUrl}"

# API
PORT=${apiPort}
NODE_ENV="${environment}"
JWT_SECRET="${jwtSecret}"
CORS_ORIGIN="*"

# Web
NEXT_PUBLIC_API_URL="${webApiUrl}"
`;

    writeFileSync(envPath, envContent);
    console.log(chalk.green(`\nCreated .env file at ${envPath}\n`));

    // Ask if user wants to start services
    const startServices = await confirm({
      message: "Start Docker services now?",
      default: true,
    });

    if (startServices) {
      console.log(chalk.blue("\nStarting Docker services...\n"));
      try {
        await execa("docker", ["compose", "up", "-d", "db"], {
          stdio: "inherit",
        });
        console.log(chalk.yellow("\nWaiting for database to be healthy..."));
        await new Promise((r) => setTimeout(r, 5000));

        const runMigrations = await confirm({
          message: "Run database migrations?",
          default: true,
        });

        if (runMigrations) {
          console.log(chalk.blue("\nRunning migrations...\n"));
          await execa("pnpm", ["--filter", "api", "migration:run"], {
            stdio: "inherit",
          });
          console.log(chalk.green("\nMigrations completed"));
        }

        console.log(chalk.green.bold("\nSetup complete!\n"));
        console.log(chalk.cyan("Next steps:"));
        console.log(
          chalk.white("  1. Run: pnpm dev (start development servers)"),
        );
        console.log(chalk.white("  2. API will be at: " + API_URL));
        console.log(chalk.white("  3. Web will be at: " + WEB_URL + "\n"));
      } catch (error) {
        console.error(chalk.red("\nFailed to start services:"), error);
      }
    } else {
      console.log(chalk.green.bold("\nSetup complete!\n"));
      console.log(chalk.cyan("Next steps:"));
      console.log(chalk.white("  1. Run: docker compose up -d db"));
      console.log(chalk.white("  2. Run: pnpm --filter api migration:run"));
      console.log(chalk.white("  3. Run: pnpm dev\n"));
    }
  });

program
  .command("doctor")
  .description("Check health (dependencies, docker, env)")
  .action(async () => {
    console.log(chalk.blue("Checking system health...\n"));

    // Node Version
    try {
      const { stdout } = await execa("node", ["--version"]);
      console.log(chalk.green(`✓ Node.js: ${stdout}`));
    } catch {
      console.log(chalk.red("✗ Node.js not found"));
    }

    // PNPM
    try {
      const { stdout } = await execa("pnpm", ["--version"]);
      console.log(chalk.green(`✓ PNPM: ${stdout}`));
    } catch {
      console.log(chalk.red("✗ PNPM not found"));
    }

    // Docker
    try {
      await execa("docker", ["info"], { stdio: "pipe" });
      console.log(chalk.green("✓ Docker is running"));
    } catch {
      console.log(chalk.red("✗ Docker is NOT running"));
    }

    // Check .env file
    if (existsSync(join(process.cwd(), ".env"))) {
      console.log(chalk.green("✓ .env file exists"));
    } else {
      console.log(chalk.yellow("⚠ .env file not found (run: evently setup)"));
    }

    console.log("");
  });

program
  .command("db")
  .description("Database operations")
  .argument("<action>", "Action to perform: migrate, seed, reset")
  .action(async (action: string) => {
    console.log(chalk.blue(`Running DB Action: ${action}\n`));

    if (action === "migrate") {
      await execa("pnpm", ["--filter", "api", "migration:run"], {
        stdio: "inherit",
      });
    } else if (action === "reset") {
      await execa("docker", ["compose", "down", "-v"], { stdio: "inherit" });
      await execa("docker", ["compose", "up", "-d", "db"], {
        stdio: "inherit",
      });
      console.log(chalk.yellow("Waiting for DB to start..."));
      await new Promise((r) => setTimeout(r, 5000));
      await execa("pnpm", ["--filter", "api", "migration:run"], {
        stdio: "inherit",
      });
    } else {
      console.log(chalk.red(`Unknown action: ${action}`));
      console.log(chalk.white("Available actions: migrate, reset"));
    }
  });

program
  .command("gen")
  .description("Generators")
  .argument("<type>", "Type to generate: api-client, module")
  .argument("[name]", "Name for module generator")
  .action(async (type: string, name?: string) => {
    if (type === "api-client") {
      console.log(chalk.blue("Generating API Client...\n"));
      try {
        await execa("pnpm", ["--filter", "client", "generate"], {
          stdio: "inherit",
        });
        console.log(chalk.green("\nClient generated successfully"));
      } catch {
        console.error(chalk.red("Failed to generate client. Is API running?"));
      }
    } else if (type === "module") {
      if (!name) {
        console.error(
          chalk.red("Please provide a module name: evently gen module <name>"),
        );
        return;
      }
      console.log(chalk.blue(`Scaffolding module "${name}" in API...\n`));
      try {
        await execa(
          "pnpm",
          [
            "--filter",
            "api",
            "exec",
            "nest",
            "g",
            "resource",
            `modules/${name}`,
          ],
          { stdio: "inherit" },
        );
        console.log(chalk.green(`\nModule "${name}" created successfully`));
      } catch {
        console.error(chalk.red("Failed to scaffold module"));
      }
    } else {
      console.log(chalk.red(`Unknown generator: ${type}`));
      console.log(chalk.white("Available generators: api-client, module"));
    }
  });

program
  .command("demo")
  .description("Run automated platform demonstration")
  .action(async () => {
    console.log(chalk.bold.blue("\n🎉 Evently Platform Demonstration\n"));
    console.log("This will demonstrate the platform features including:");
    console.log("  • Database connectivity");
    console.log("  • API health check");
    console.log("  • Event CRUD operations");
    console.log("  • Security headers");
    console.log("  • Request correlation IDs\n");

    try {
      // Check if database is running
      console.log(chalk.blue("Checking database connection..."));
      await execa("docker", ["compose", "ps", "db"], { stdio: "pipe" });

      // Check if API is running by testing health endpoint
      console.log(chalk.blue("Checking API server..."));
      try {
        await execa("curl", ["-f", "-s", `${API_URL}/health`]);
      } catch {
        console.log(chalk.yellow("API not running. Starting API server..."));
        console.log(
          chalk.yellow("Please start the API with: pnpm --filter api dev"),
        );
        console.log(chalk.yellow("Then run the demo again."));
        return;
      }

      console.log(chalk.green("✓ Database and API are running\n"));

      // Demonstrate health check
      console.log(chalk.blue.bold("=== Health Check ==="));
      const { stdout: healthOutput } = await execa("curl", [
        "-s",
        `${API_URL}/health`,
      ]);
      console.log(healthOutput);
      console.log("");

      // Create sample events
      console.log(chalk.blue.bold("=== Creating Sample Events ==="));

      const event1 = {
        name: "Tech Conference 2026",
        date: "2026-06-15T09:00:00Z",
        description: "Annual technology conference",
        place: "San Francisco, CA",
      };

      const { stdout: createOutput1 } = await execa("curl", [
        "-s",
        "-X",
        "POST",
        `${API_URL}/events`,
        "-H",
        "Content-Type: application/json",
        "-d",
        JSON.stringify(event1),
      ]);
      console.log("Event 1 created:");
      console.log(createOutput1);
      console.log("");

      const event2 = {
        name: "Product Launch",
        date: "2026-12-31T18:00:00Z",
        description: "New product unveiling",
        place: "New York, NY",
      };

      const { stdout: createOutput2 } = await execa("curl", [
        "-s",
        "-X",
        "POST",
        `${API_URL}/events`,
        "-H",
        "Content-Type: application/json",
        "-d",
        JSON.stringify(event2),
      ]);
      console.log("Event 2 created:");
      console.log(createOutput2);
      console.log("");

      // List all events
      console.log(chalk.blue.bold("=== Listing All Events ==="));
      const { stdout: listOutput } = await execa("curl", [
        "-s",
        `${API_URL}/events`,
      ]);
      console.log(listOutput);
      console.log("");

      // Get single event
      console.log(chalk.blue.bold("=== Get Single Event (ID: 1) ==="));
      const { stdout: getOutput } = await execa("curl", [
        "-s",
        `${API_URL}/events/1`,
      ]);
      console.log(getOutput);
      console.log("");

      // Update event
      console.log(chalk.blue.bold("=== Update Event (ID: 1) ==="));
      const updatedEvent = {
        name: "Tech Conference 2026 - UPDATED",
        date: "2026-06-16T09:00:00Z",
        description: "Annual technology conference - Date changed",
        place: "San Francisco, CA",
      };

      const { stdout: updateOutput } = await execa("curl", [
        "-s",
        "-X",
        "PUT",
        `${API_URL}/events/1`,
        "-H",
        "Content-Type: application/json",
        "-d",
        JSON.stringify(updatedEvent),
      ]);
      console.log(updateOutput);
      console.log("");

      // Check security headers
      console.log(chalk.blue.bold("=== Security Headers ==="));
      const { stdout: headersOutput } = await execa("curl", [
        "-I",
        "-s",
        `${API_URL}/health`,
      ]);
      const relevantHeaders = headersOutput
        .split("\n")
        .filter((line: string) =>
          line.match(
            /X-Frame-Options|X-Content-Type-Options|Strict-Transport-Security|Content-Security-Policy/i,
          ),
        );
      relevantHeaders.forEach((header: string) => console.log(header.trim()));
      console.log("");

      // Show API documentation
      console.log(chalk.blue.bold("=== API Documentation ==="));
      console.log(`Swagger UI: ${API_URL}/docs`);
      console.log(`OpenAPI JSON: ${API_URL}/docs-json`);
      console.log("");

      console.log(chalk.green.bold("✓ Demo completed successfully\n"));
      console.log("Summary:");
      console.log("  • Health check: OK");
      console.log("  • Created 2 sample events");
      console.log("  • Demonstrated CRUD operations");
      console.log("  • Verified security headers");
      console.log("  • All features working correctly");
      console.log("");
      console.log("Access the application:");
      console.log(`  • API: ${API_URL}`);
      console.log(`  • Docs: ${API_URL}/docs`);
      console.log(`  • Health: ${API_URL}/health`);
      console.log("");
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(chalk.red("\nDemo failed:"), message);
      console.log(chalk.yellow("\nEnsure the following are running:"));
      console.log("  1. Database: docker compose up -d db");
      console.log("  2. API: pnpm --filter api dev");
    }
  });

program
  .command("status")
  .description("Show current project status")
  .action(async () => {
    console.log(chalk.bold.blue("\n📊 Evently Project Status\n"));

    // Check Docker containers
    console.log(chalk.cyan("Docker Services:"));
    try {
      const { stdout } = await execa("docker", [
        "compose",
        "ps",
        "--format",
        "table {{.Name}}\t{{.Status}}\t{{.Ports}}",
      ]);
      console.log(stdout);
    } catch {
      console.log(chalk.yellow("  Docker not running or no containers"));
    }
    console.log("");

    // Check API health
    console.log(chalk.cyan("API Status:"));
    try {
      const { stdout } = await execa("curl", ["-s", `${API_URL}/health`]);
      const health = JSON.parse(stdout);
      console.log(chalk.green(`  ✓ API: ${health.data?.status || "ok"}`));
      console.log(
        chalk.green(
          `  ✓ Database: ${health.data?.info?.database?.status || "unknown"}`,
        ),
      );
    } catch {
      console.log(chalk.red("  ✗ API not responding"));
    }
    console.log("");

    // Show URLs
    console.log(chalk.cyan("URLs:"));
    console.log(`  API:  ${API_URL}`);
    console.log(`  Web:  ${WEB_URL}`);
    console.log(`  Docs: ${API_URL}/docs`);
    console.log("");
  });

program.parse(process.argv);
